### ISSUE TITLE
Fill out the issue backlog

### ISSUE THREAD

**Issue by jameslamb** [uptake/octopus#4]
The README for this project mentions a few welcome extensions, such as integration with other SCM tools like Gitlab and GitHub.

Can you document any ideas you have for future development in issues here on Github?

On `pkgnet`, we've found GitHub's "Milestone" feature really useful for organizing issues: https://github.com/UptakeOpenSource/pkgnet/milestones

**Comment by gkman** [comment]
@jameslamb would you please confirm this has been completed by the addition of #7 and #8

**Comment by jameslamb** [comment]
@gkman yeah totally! Thanks to you and @simsalabim for breathing some life into this project. Super cool.

**Comment by gkman** [comment]
Any time buddy ❤️ @jameslamb
